ingressroute:
  enabled: true  
  name: traefik-ingressroute
  namespace: default  
  annotations:
    ingressClass: traefik-external  # Specify the IngressClass

  entryPoints:
    - web  # This is for HTTP (port 80)

  routes:
    - match: "Host(`tr.technoor.me`) && PathPrefix(`/`)"
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService


