{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressroute.name }}
  namespace: {{ .Values.ingressroute.namespace }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressroute.annotations.ingressClass }}"
spec:
  entryPoints:
    {{- toYaml .Values.ingressroute.entryPoints | nindent 4 }}
  routes:
  {{- range .Values.ingressroute.routes }}
    - match: {{ .match | quote }}
      kind: {{ .kind }}
      services:
      {{- range .services }}
        - name: {{ .name }}
          kind: {{ .kind }}
          {{- if .port }}
          port: {{ .port }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
